name: Prisma Cloud IaC Scan Example
on: 
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  prisma_cloud_iac_scan:
    runs-on: ubuntu-latest
    name: Run Prisma Cloud IaC Scan to check 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master 
        env:
          PRISMA_API_URL: https://api.uk.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          
        - name: Expose report
          uses: actions/upload-artifact@v2
          with:
	          name: SARIF results
	          path: results.sarif

# Uploads results.sarif to GitHub repository using the upload-sarif action

        - uses: github/codeql-action/upload-sarif@v1
          with:
# Path to SARIF file relative to the root of the repository
	          sarif_file: results.sarif
